"""расширение UserProfile под google авторизацию

Revision ID: 48b5071e0b16
Revises: 3cbc91f1e557
Create Date: 2025-04-17 21:13:58.811713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b5071e0b16'
down_revision: Union[str, None] = '3cbc91f1e557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfile', sa.Column('email', sa.String(), nullable=True))
    op.add_column('UserProfile', sa.Column('name', sa.String(), nullable=True))
    op.add_column('UserProfile', sa.Column('given_name', sa.String(), nullable=True))
    op.add_column('UserProfile', sa.Column('family_name', sa.String(), nullable=True))
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('UserProfile', 'family_name')
    op.drop_column('UserProfile', 'given_name')
    op.drop_column('UserProfile', 'name')
    op.drop_column('UserProfile', 'email')
    # ### end Alembic commands ###
