"""Test async

Revision ID: 7ea4b5c5a56c
Revises: 0ae1e456bb7d
Create Date: 2025-05-02 17:47:08.867597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea4b5c5a56c'
down_revision: Union[str, None] = '0ae1e456bb7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Category', sa.Column('test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Category', 'test')
    # ### end Alembic commands ###
