"""еще попытка поменять Categories на Category

Revision ID: fc2db6e8d217
Revises: a2f60648ff66
Create Date: 2025-03-19 21:15:12.572879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2db6e8d217'
down_revision: Union[str, None] = 'a2f60648ff66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Categories')
    op.add_column('Tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_column('Tasks', 'categories_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('categories_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Tasks', 'category_id')
    op.create_table('Categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Categories_pkey')
    )
    op.drop_table('Category')
    # ### end Alembic commands ###
